import { useMemo, useState } from "react";
import { Text, View } from "react-native";
import { useAuth } from "@clerk/expo";
import { useApi } from "@/src/hooks";
import { apiRequest } from "@/src/services/api";
import { BackButton, Button, Card, EmptyState, Screen, SelectField, TextField } from "@/src/components";
import { styles } from "@/src/theme";
type Weight = { id: string; weight: number; unit: "kg" | "lb"; loggedAt: string };
const ranges = [{ label: "7 days", value: "7" }, { label: "30 days", value: "30" }, { label: "90 days", value: "90" }, { label: "All", value: "all" }];
export default function ProgressScreen() {
  const { getToken } = useAuth(); const [weight, setWeight] = useState(""); const [unit, setUnit] = useState<"kg" | "lb">("kg"); const [range, setRange] = useState("30"); const [message, setMessage] = useState(""); const weights = useApi<Weight[]>("/api/weight");
  async function save() { const value = Number(weight); if (!Number.isFinite(value) || value <= 0) { setMessage("Enter a valid weight."); return; } try { await apiRequest("/api/weight", { method: "POST", token: await getToken(), body: JSON.stringify({ weight: value, unit }) }); setWeight(""); setMessage("Weight check-in saved."); await weights.refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not save weight."); } }
  async function remove(id: string) { try { await apiRequest(`/api/weight?id=${encodeURIComponent(id)}`, { method: "DELETE", token: await getToken() }); await weights.refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not remove entry."); } }
  const visible = useMemo(() => range === "all" ? weights.data ?? [] : (weights.data ?? []).filter((item) => Date.now() - new Date(item.loggedAt).getTime() <= Number(range) * 86400000), [weights.data, range]);
  const latest = weights.data?.[0]; const previous = weights.data?.[1]; const change = latest && previous && latest.unit === previous.unit ? latest.weight - previous.weight : null;
  const chronological = [...visible].sort((a, b) => a.loggedAt.localeCompare(b.loggedAt)); const max = Math.max(...chronological.map((item) => item.weight), 1); const min = Math.min(...chronological.map((item) => item.weight), max);
  return <Screen><BackButton /><Text style={styles.eyebrow}>NOTICE YOUR PATTERNS</Text><Text style={styles.title}>Your progress.</Text><Text style={styles.body}>Progress is more than a number. Notice what is changing without turning it into a target.</Text>{message && <Text style={styles.success}>{message}</Text>}
    <View style={styles.metricGrid}><Card style={styles.metricCard}><Text style={styles.caption}>Latest weight</Text><Text style={styles.metric}>{latest ? `${latest.weight} ${latest.unit}` : "—"}</Text><Text style={styles.caption}>{latest ? new Date(latest.loggedAt).toLocaleDateString() : "No check-ins yet"}</Text></Card><Card style={styles.metricCard}><Text style={styles.caption}>Change from previous</Text><Text style={styles.metric}>{change === null ? "—" : `${change > 0 ? "+" : ""}${change.toFixed(1)} ${latest?.unit}`}</Text><Text style={styles.caption}>{change === null ? "Add another check-in" : "Not a medical measure"}</Text></Card></View>
    <Card><Text style={styles.sectionTitle}>Weight check-in</Text><TextField label="Weight" placeholder="Your weight" value={weight} onChangeText={setWeight} keyboardType="decimal-pad" /><SelectField label="Unit" value={unit} options={[{ label: "Kilograms (kg)", value: "kg" }, { label: "Pounds (lb)", value: "lb" }]} onChange={(value) => setUnit(value as "kg" | "lb")} /><Button label="Save check-in" onPress={save} /></Card>
    <Card><Text style={styles.sectionTitle}>Weight trend</Text><View style={styles.chipRow}>{ranges.map((item) => <Text key={item.value} onPress={() => setRange(item.value)} style={[styles.chip, range === item.value && styles.chipActive, styles.chipText]}>{item.label}</Text>)}</View>{chronological.length > 1 ? <View style={styles.chart}>{chronological.map((item) => <View key={item.id} style={styles.chartColumn}><View style={[styles.chartBar, { height: `${Math.max(15, ((item.weight - min + (max === min ? 1 : 0)) / (max - min + (max === min ? 1 : 0))) * 85 + 15)}%` }]} /><Text style={styles.chartLabel}>{new Date(item.loggedAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</Text></View>)}</View> : <EmptyState title="Your trend will appear here" body="Log at least two check-ins to see a trend." />}</Card>
    <Card><Text style={styles.sectionTitle}>Check-in history</Text>{weights.loading && <EmptyState title="Loading history..." body="Fetching your saved check-ins." />}{!weights.loading && !visible.length && <EmptyState title="No check-ins in this range" body="Log a check-in to start seeing your trend." />}{visible.map((item) => <View key={item.id} style={styles.loggedRow}><View><Text style={styles.strong}>{item.weight} {item.unit}</Text><Text style={styles.caption}>{new Date(item.loggedAt).toLocaleDateString()}</Text></View><Text onPress={() => remove(item.id)} style={styles.link}>Remove</Text></View>)}</Card>
  </Screen>;
}
