import { useMemo, useState } from "react";
import { Text, View } from "react-native";
import { useApi } from "@/src/hooks";
import { BackButton, Card, EmptyState, Screen } from "@/src/components";
import { styles } from "@/src/theme";
type Day = { date: string; calories: number; protein: number; carbohydrates: number; fat: number; fiber: number; meals: number };
type Report = { range: number; days: Day[]; totals: Day; meals: number; weights: { id: string; weight: number; unit: string; loggedAt: string }[] };
const ranges = [{ value: "1", label: "Today" }, { value: "7", label: "Last 7 days" }, { value: "30", label: "Last 30 days" }];
export default function ReportsScreen() {
  const [range, setRange] = useState("7"); const report = useApi<Report>(`/api/reports?days=${range}`);
  const average = (key: keyof Day) => report.data ? report.data.days.reduce((sum, day) => sum + Number(day[key] ?? 0), 0) / report.data.days.length : 0;
  const activeDays = report.data?.days.filter((day) => day.meals > 0).length ?? 0; const maxCalories = Math.max(...(report.data?.days.map((day) => day.calories) ?? [1]), 1);
  const weightSummary = useMemo(() => { const weights = report.data?.weights ?? []; if (!weights.length) return null; const first = weights[0]; const last = weights[weights.length - 1]; return { first, last, change: first.unit === last.unit ? last.weight - first.weight : null }; }, [report.data]);
  return <Screen><BackButton /><Text style={styles.eyebrow}>YOUR BIGGER PICTURE</Text><Text style={styles.title}>Nutrition report.</Text><Text style={styles.body}>A calm snapshot calculated from your actual food and weight logs.</Text><View style={styles.chipRow}>{ranges.map((item) => <Text key={item.value} onPress={() => setRange(item.value)} style={[styles.chip, range === item.value && styles.chipActive, styles.chipText]}>{item.label}</Text>)}</View>{report.loading && <EmptyState title="Loading report..." body="Calculating your real nutrition averages." />}{report.error && <Text style={styles.error}>{report.error}</Text>}{report.data && <><View style={styles.metricGrid}>{[["Avg calories", `${Math.round(average("calories"))} kcal`], ["Avg protein", `${average("protein").toFixed(1)}g`], ["Avg carbs", `${average("carbohydrates").toFixed(1)}g`], ["Avg fat", `${average("fat").toFixed(1)}g`], ["Avg fiber", `${average("fiber").toFixed(1)}g`], ["Logged meals", String(report.data.meals)]].map(([label, value]) => <Card key={label} style={styles.metricCard}><Text style={styles.caption}>{label}</Text><Text style={styles.metric}>{value}</Text><Text style={styles.caption}>Actual logged data</Text></Card>)}</View><Card><Text style={styles.sectionTitle}>Daily calorie trend</Text>{report.data.meals ? <View style={styles.chart}>{report.data.days.map((day) => <View key={day.date} style={styles.chartColumn}><View style={[styles.chartBar, { height: `${Math.max(8, day.calories / maxCalories * 100)}%` }]} /><Text style={styles.chartLabel}>{new Date(`${day.date}T00:00:00Z`).toLocaleDateString(undefined, { weekday: "short" })}</Text></View>)}</View> : <EmptyState title="No food logged in this range" body="Log a meal to see a real trend." />}<Text style={styles.body}>Protein average: {average("protein").toFixed(1)}g/day · Fiber average: {average("fiber").toFixed(1)}g/day.</Text></Card><Card><Text style={styles.sectionTitle}>Consistency and weight</Text><Text style={styles.body}>{activeDays} of {report.data.range} days include at least one logged meal ({Math.round(activeDays / report.data.range * 100)}%).</Text>{weightSummary ? <Text style={styles.body}>Weight changed {weightSummary.change === null ? "between entries with different units" : `${weightSummary.change > 0 ? "+" : ""}${weightSummary.change.toFixed(1)} ${weightSummary.last.unit}`} across available history.</Text> : <Text style={styles.caption}>No weight history yet. Add check-ins in Progress to see a trend.</Text>}</Card></>}</Screen>;
}
