import { useState } from "react";
import { Text } from "react-native";
import { useApi } from "@/src/hooks";
import { Card, EmptyState, Screen } from "@/src/components";
import { styles } from "@/src/theme";
type Report = { totals: { calories: number; protein: number; carbohydrates: number; fat: number; fiber: number }; meals: number; days: { date: string; calories: number; meals: number }[]; weights: { weight: number; unit: string; loggedAt: string }[] };
export default function ReportsScreen() {
  const [days, setDays] = useState<1 | 7 | 30>(7); const report = useApi<Report>(`/api/reports?days=${days}`);
  return <Screen><Text style={styles.eyebrow}>YOUR PATTERNS</Text><Text style={styles.title}>Nutrition reports.</Text><Text style={styles.body}>Only logged food and weight data are included.</Text><Text style={styles.action} onPress={() => setDays(1)}>Today</Text><Text style={styles.action} onPress={() => setDays(7)}>7 days</Text><Text style={styles.action} onPress={() => setDays(30)}>30 days</Text>{report.loading && <EmptyState title="Loading report..." body="Calculating your real nutrition averages." />}{report.error && <Text style={styles.error}>{report.error}</Text>}{report.data && <><Card><Text style={styles.sectionTitle}>Totals</Text><Text style={styles.body}>Calories {Math.round(report.data.totals.calories)} · Protein {Math.round(report.data.totals.protein)}g</Text><Text style={styles.body}>Carbs {Math.round(report.data.totals.carbohydrates)}g · Fat {Math.round(report.data.totals.fat)}g · Fiber {Math.round(report.data.totals.fiber)}g</Text><Text style={styles.caption}>{report.data.meals} logged meals in this period.</Text></Card><Card><Text style={styles.sectionTitle}>Daily activity</Text>{report.data.days.filter((day) => day.meals).map((day) => <Text key={day.date} style={styles.body}>{day.date}: {day.meals} meals · {Math.round(day.calories)} kcal</Text>)}</Card><Card><Text style={styles.sectionTitle}>Weight trend</Text>{report.data.weights.length ? <Text style={styles.body}>{report.data.weights.length} weight check-ins recorded.</Text> : <Text style={styles.caption}>No weight data for this account yet.</Text>}</Card></>}</Screen>;
}
