import { Link, router, useLocalSearchParams } from "expo-router";
import { Text, View } from "react-native";
import { useEffect, useState } from "react";
import { useAuth } from "@clerk/expo";
import { apiRequest } from "@/src/services/api";
import { BackButton, Button, Card, EmptyState, Screen } from "@/src/components";
import { styles } from "@/src/theme";
import { useApi } from "@/src/hooks";
import type { Data } from "@/src/workout-data";
import { ExerciseImage } from "@/src/workout-ui";
export default function ActiveWorkout() {
  const { id, active } = useLocalSearchParams<{ id: string; active?: string }>(); const { getToken } = useAuth(); const data = useApi<Data>("/api/workouts"); const workout = data.data?.workouts.find((item) => item.id === id); const [index, setIndex] = useState(0); const [startedAt] = useState(Date.now()); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [completedCount, setCompletedCount] = useState(0); const [resting, setResting] = useState(false); const [restSeconds, setRestSeconds] = useState(0);
  useEffect(() => { if (!resting) return; const timer = setInterval(() => setRestSeconds((current) => current - 1), 1000); return () => clearInterval(timer); }, [resting]);
  useEffect(() => { if (resting && restSeconds <= 0) { setResting(false); setIndex((current) => current + 1); } }, [resting, restSeconds]);
  if (data.loading) return <Screen centered><EmptyState title="Loading workout..." body="Getting your session ready." /></Screen>;
  if (!workout) return <Screen><BackButton href="/(tabs)/workout" /><EmptyState title="Workout not found" body="Choose another plan to get moving." /></Screen>;
  if (active !== "1") return <Screen><BackButton href="/(tabs)/workout" /><ExerciseImage uri={workout.image} style={styles.detailImage} /><Text style={styles.eyebrow}>{workout.category} · {workout.difficulty}</Text><Text style={styles.title}>{workout.name}</Text><Text style={styles.body}>{workout.description}</Text><Button label="Start workout" onPress={() => router.replace({ pathname: "/workout/[id]", params: { id: workout.id, active: "1" } })} /><Card><View style={styles.detailStats}><View style={styles.detailStat}><Text style={styles.caption}>DURATION</Text><Text style={styles.detailStatValue}>{workout.duration} min</Text></View><View style={styles.detailStat}><Text style={styles.caption}>EXERCISES</Text><Text style={styles.detailStatValue}>{workout.exercises.length}</Text></View></View></Card><Text style={styles.sectionTitle}>Exercises</Text>{workout.exercises.map(({ exerciseId }) => { const item = data.data?.exercises.find((exercise) => exercise.id === exerciseId); return item ? <Link key={item.id} href={{ pathname: "/exercise/[id]", params: { id: item.id } }} style={styles.libraryRow}><ExerciseImage uri={item.image} style={styles.libraryImage} /><View style={styles.libraryCopy}><Text style={styles.sectionTitle}>{item.name}</Text><Text style={styles.caption}>{item.muscleGroup} · {item.sets} sets{item.reps ? ` · ${item.reps} reps` : ""}</Text></View></Link> : null; })}</Screen>;
  const activeWorkout = workout;
  const exerciseId = activeWorkout.exercises[index]?.exerciseId; const exercise = data.data?.exercises.find((item) => item.id === exerciseId);
  async function saveWorkout(exercisesCompleted = completedCount) { setSaving(true); setError(""); try { const result = await apiRequest<{ workoutsCompleted: number; streak: number; totalMinutes: number }>("/api/workouts/progress", { method: "POST", token: await getToken(), body: JSON.stringify({ workoutId: activeWorkout.id, workoutName: activeWorkout.name, durationMinutes: Math.max(1, Math.round((Date.now() - startedAt) / 60000)), exercisesCompleted }) }); router.replace({ pathname: "/workout-complete", params: { workoutName: activeWorkout.name, duration: String(Math.max(1, Math.round((Date.now() - startedAt) / 60000))), exercises: String(exercisesCompleted), workouts: String(result.workoutsCompleted), streak: String(result.streak) } }); } catch (err) { setError(err instanceof Error ? err.message : "Could not save this workout."); } finally { setSaving(false); } }
  function complete() { const nextCount = completedCount + 1; setCompletedCount(nextCount); if (index < activeWorkout.exercises.length - 1) { setRestSeconds(exercise?.rest ?? 30); setResting(true); } else void saveWorkout(nextCount); }
  const skip = () => { if (index < activeWorkout.exercises.length - 1) setIndex(index + 1); else void saveWorkout(); };
  if (resting) return <Screen centered><Text style={styles.eyebrow}>REST</Text><Card style={styles.restCard}><Text style={styles.restLabel}>REST</Text><Text style={styles.restValue}>{restSeconds}</Text><Text style={styles.body}>seconds</Text><View style={styles.workoutProgress}><View style={[styles.workoutProgressFill, { width: `${Math.max(0, (restSeconds / (exercise?.rest ?? 30)) * 100)}%` }]} /></View><Button label="Skip rest" variant="secondary" onPress={() => { setResting(false); setIndex(index + 1); }} /></Card><Text style={styles.caption}>Your next exercise is ready when you are.</Text></Screen>;
  return <Screen><BackButton href="/(tabs)/workout" /><Text style={styles.eyebrow}>EXERCISE {index + 1} OF {activeWorkout.exercises.length}</Text><Text style={styles.title}>{activeWorkout.name}</Text><View style={styles.workoutProgress}><View style={[styles.workoutProgressFill, { width: `${((index + 1) / activeWorkout.exercises.length) * 100}%` }]} /></View>{error && <Text style={styles.error}>{error}</Text>}{exercise && <><Card><ExerciseImage uri={exercise.image} style={styles.activeExerciseImage} /><Text style={styles.sectionTitle}>{exercise.name}</Text><Text style={styles.caption}>{exercise.sets} × {exercise.reps ?? `${exercise.duration} sec`} · Rest: {exercise.rest} sec</Text></Card><Card><Text style={styles.sectionTitle}>Instructions</Text>{exercise.instructions.map((line) => <Text key={line} style={styles.body}>• {line}</Text>)}</Card><View style={styles.workoutControls}>{index > 0 && <Button label="Previous" variant="secondary" onPress={() => setIndex(index - 1)} />}<Button label="Skip" variant="secondary" onPress={skip} /><Button label={saving ? "Saving..." : "Complete"} onPress={complete} disabled={saving} />{index < activeWorkout.exercises.length - 1 && <Button label="Next" variant="secondary" onPress={() => setIndex(index + 1)} />}</View><Text style={styles.caption}>Choose a comfortable pace. Stop if you experience pain, dizziness, or unusual discomfort.</Text></>}</Screen>;
}
