"use client";

import { useEffect, useMemo, useState } from "react";
import { formatNumber } from "@/lib/nutrition";

type Day = { date: string; calories: number; protein: number; carbohydrates: number; fat: number; fiber: number; meals: number };
type Report = { range: number; days: Day[]; totals: Day; meals: number; weights: { id: string; weight: number; unit: string; loggedAt: string }[] };

export default function ReportsPage() {
  const [range, setRange] = useState("7"); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { setLoading(true); fetch(`/api/reports?days=${range}`).then(async (response) => { if (!response.ok) throw new Error((await response.json()).message ?? "Unable to load report."); return response.json() as Promise<Report>; }).then(setReport).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load report.")).finally(() => setLoading(false)); }, [range]);
  const average = (key: keyof Day) => report ? report.days.reduce((sum, day) => sum + Number(day[key] ?? 0), 0) / report.days.length : 0;
  const activeDays = report?.days.filter((day) => day.meals > 0).length ?? 0;
  const maxCalories = Math.max(...(report?.days.map((day) => day.calories) ?? [1]), 1);
  const weightSummary = useMemo(() => { if (!report?.weights.length) return null; const first = report.weights[0]; const last = report.weights[report.weights.length - 1]; return { first, last, change: last.unit === first.unit ? last.weight - first.weight : null }; }, [report]);
  return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Your bigger picture</div><h1>Nutrition report.</h1><p>A calm snapshot calculated from your actual food and weight logs.</p></div><button className="button button-ghost" onClick={() => window.print()}>Print report</button></div><div className="toolbar">{[["1", "Today"], ["7", "Last 7 days"], ["30", "Last 30 days"]].map(([value, label]) => <button type="button" className={`button ${range === value ? "button-primary" : "button-ghost"}`} key={value} onClick={() => setRange(value)}>{label}</button>)}</div>{error && <div className="error-box" role="alert">{error}</div>}{loading || !report ? <div className="app-card loading-state">Loading your nutrition report…</div> : <><div className="stats-grid">{[["Average calories", `${Math.round(average("calories"))} kcal`], ["Average protein", `${formatNumber(average("protein"))}g`], ["Average carbohydrates", `${formatNumber(average("carbohydrates"))}g`], ["Average fat", `${formatNumber(average("fat"))}g`], ["Average fiber", `${formatNumber(average("fiber"))}g`], ["Logged meals", String(report.meals)]].map(([label, value]) => <div className="app-card stat-card" key={label}><small>{label}</small><strong>{value}</strong><span>Per day average except logged meals</span></div>)}</div><div className="dashboard-two" style={{ marginTop: 20 }}><section className="app-card"><h2 className="section-title">Daily calorie trend</h2>{report.meals ? <div className="report-chart" aria-label={`Calories logged across the last ${report.range} days`}>{report.days.map((day) => <div className="report-bar" key={day.date} style={{ height: `${Math.max(8, day.calories / maxCalories * 100)}%` }}><strong>{new Date(`${day.date}T00:00:00Z`).toLocaleDateString(undefined, { weekday: "short" })}</strong></div>)}</div> : <div className="empty-state"><strong>No food logged in this range</strong><span>Log a meal to see a real trend.</span></div>}<p className="page-copy" style={{ marginTop: 30 }}>Protein average: {formatNumber(average("protein"))}g per day. Fiber average: {formatNumber(average("fiber"))}g per day.</p></section><section className="app-card"><h2 className="section-title">Consistency and weight</h2><p className="page-copy">{activeDays} of {report.range} days include at least one logged meal ({Math.round(activeDays / report.range * 100)}%).</p>{weightSummary ? <p className="page-copy">Weight changed {weightSummary.change === null ? "between entries with different units" : `${weightSummary.change > 0 ? "+" : ""}${weightSummary.change.toFixed(1)} ${weightSummary.last.unit}`} across the available history.</p> : <div className="empty-state compact"><strong>No weight history yet</strong><span>Add check-ins in Progress to see an actual weight trend.</span></div>}<span className="pill">Only logged data is shown</span></section></div></>}</div>;
}
