import { useMemo, useRef, useState } from "react";
import { Modal, Pressable, Text, View } from "react-native";
import { useAuth } from "@clerk/expo";
import { useApi } from "@/src/hooks";
import { apiRequest } from "@/src/services/api";
import { Button, Card, EmptyState, ProgressBar, Screen, TextField } from "@/src/components";
import { styles } from "@/src/theme";
import type { Food, Meal, Recipe } from "@/src/types";

type Plan = { weekStart: string; meals: Meal[] };
const monday = (offset = 0) => { const date = new Date(); const day = date.getUTCDay(); date.setUTCDate(date.getUTCDate() - (day === 0 ? 6 : day - 1) + offset * 7); return date.toISOString().slice(0, 10); };
const dates = (start: string) => Array.from({ length: 7 }, (_, index) => { const date = new Date(`${start}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + index); return date.toISOString().slice(0, 10); });
const formatDay = (date: string) => new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric" }).format(new Date(`${date}T00:00:00Z`));
const mealIcon: Record<string, string> = { breakfast: "☀️", lunch: "🥗", dinner: "🍲", snack: "🍎" };
export default function PlannerScreen() {
  const { getToken } = useAuth(); const [offset, setOffset] = useState(0); const [selectedDate, setSelectedDate] = useState(""); const [mealType, setMealType] = useState("breakfast"); const [query, setQuery] = useState(""); const [savingMeal, setSavingMeal] = useState(false); const [message, setMessage] = useState(""); const mealSavingRef = useRef(false); const week = monday(offset);
  const plan = useApi<Plan>(`/api/meal-plans?weekStart=${week}`); const foods = useApi<Food[]>("/api/foods"); const recipes = useApi<Recipe[]>("/api/recipes");
  const [itemType, setItemType] = useState<"food" | "recipe">("food"); const [servings, setServings] = useState("1");
  const filteredItems = useMemo(() => { const normalized = query.trim().toLowerCase(); const items = itemType === "food" ? foods.data ?? [] : recipes.data ?? []; return items.filter((item) => !normalized || `${item.name} ${"cuisine" in item ? item.cuisine : item.description}`.toLowerCase().includes(normalized)); }, [foods.data, recipes.data, itemType, query]);
  const planTotals = useMemo(() => plan.data?.meals.reduce((totals, meal) => ({ calories: totals.calories + meal.calories, protein: totals.protein + meal.protein, carbohydrates: totals.carbohydrates + meal.carbohydrates, fat: totals.fat + meal.fat }), { calories: 0, protein: 0, carbohydrates: 0, fat: 0 }) ?? { calories: 0, protein: 0, carbohydrates: 0, fat: 0 }, [plan.data]);
  const weekDays = useMemo(() => dates(week), [week]);
  async function saveMeal(item: Food | Recipe) { if (mealSavingRef.current) return; const amount = Number(servings); if (!Number.isFinite(amount) || amount < 0.25 || amount > 20) { setMessage("Enter between 0.25 and 20 servings."); return; } mealSavingRef.current = true; setSavingMeal(true); setMessage(""); const existing = plan.data?.meals.filter((meal) => !(meal.date === selectedDate && meal.mealType === mealType)) ?? []; const next = [...existing, { date: selectedDate, mealType, itemType, itemId: item.id, servings: amount }]; try { await apiRequest("/api/meal-plans", { method: "PUT", token: await getToken(), body: JSON.stringify({ weekStart: week, meals: next }) }); setSelectedDate(""); setQuery(""); setServings("1"); await plan.refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not add this meal to your plan."); } finally { mealSavingRef.current = false; setSavingMeal(false); } }
  async function remove(mealId: string) { try { await apiRequest(`/api/meal-plans?weekStart=${week}&mealId=${encodeURIComponent(mealId)}`, { method: "DELETE", token: await getToken() }); await plan.refresh(); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not remove this meal."); } }
  return <Screen><Text style={styles.eyebrow}>PLAN WITH EASE</Text><Text style={styles.title}>Your meal planner.</Text><Text style={styles.body}>Build a flexible week from Nouriva&apos;s food and recipe library.</Text><View style={styles.plannerControls}><Button label="← Previous" variant="secondary" onPress={() => setOffset(offset - 1)} /><Button label="Next →" variant="secondary" onPress={() => setOffset(offset + 1)} /></View>
    {message && <Text style={styles.error}>{message}</Text>}{plan.loading && <EmptyState title="Loading your plan..." body="Fetching the meals saved for this week." />}{plan.error && <Text style={styles.error}>{plan.error}</Text>}{plan.data && <Card style={styles.plannerNutrition}><Text style={styles.pill}>Weekly overview</Text><Text style={styles.sectionTitle}>Weekly plan nutrition</Text><ProgressBar label="Calories" value={planTotals.calories} target={14000} unit=" kcal" /><ProgressBar label="Protein" value={planTotals.protein} target={700} unit=" g" /><ProgressBar label="Carbs" value={planTotals.carbohydrates} target={1750} unit=" g" /><ProgressBar label="Fat" value={planTotals.fat} target={490} unit=" g" /></Card>}
    {weekDays.map((date) => <Card key={date} style={styles.plannerDay}><View style={styles.plannerDayHeader}><Text style={styles.planDayTitle}>{formatDay(date)}</Text><Text style={styles.caption}>{Math.round(plan.data?.meals.filter((meal) => meal.date === date).reduce((sum, meal) => sum + meal.calories, 0) ?? 0)} kcal</Text></View>{["breakfast", "lunch", "dinner", "snack"].map((type) => { const meal = plan.data?.meals.find((item) => item.date === date && item.mealType === type); return <View key={type} style={styles.plannerSlot}><Text style={styles.mealHeading}>{mealIcon[type]}  {type.toUpperCase()}</Text>{meal ? <View><Text style={styles.body}>{meal.itemName} · {Math.round(meal.calories)} kcal</Text><Text onPress={() => remove(meal.id)} style={styles.link}>Remove</Text></View> : <Pressable accessibilityRole="button" onPress={() => { setSelectedDate(date); setMealType(type); setQuery(""); }} style={styles.addMealSlot}><Text style={styles.link}>+ Add {type}</Text></Pressable>}</View>; })}</Card>)}
    <Modal visible={Boolean(selectedDate)} transparent animationType="slide" onRequestClose={() => setSelectedDate("")}>
      <View style={styles.selectOverlay}><View style={styles.selectMenu}><Text style={styles.selectMenuTitle}>Add {mealType} for {selectedDate}</Text><View style={styles.chipRow}><Text onPress={() => setItemType("food")} style={[styles.chip, itemType === "food" && styles.chipActive, styles.chipText]}>Food</Text><Text onPress={() => setItemType("recipe")} style={[styles.chip, itemType === "recipe" && styles.chipActive, styles.chipText]}>Recipe</Text></View><TextField label="Search library" placeholder="Search foods or recipes" value={query} onChangeText={setQuery} /><TextField label="Servings" value={servings} onChangeText={setServings} keyboardType="decimal-pad" />{foods.loading || recipes.loading ? <EmptyState title="Loading library..." body="Finding saved food and recipe options." /> : !filteredItems.length ? <EmptyState title="No items found" body="Try a different search term." /> : filteredItems.slice(0, 8).map((item) => <Pressable key={item.id} accessibilityRole="button" onPress={() => saveMeal(item)} style={styles.selectOption}><Text style={styles.selectOptionText}>{item.name} · {Math.round(item.calories)} kcal</Text></Pressable>)}<Button label={savingMeal ? "Adding..." : "Cancel"} variant="secondary" onPress={() => { if (!savingMeal) setSelectedDate(""); }} /></View></View>
    </Modal>
  </Screen>;
}
