"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { GroceryListItem } from "@/types";

const categories = ["produce", "protein", "dairy", "grains", "pantry", "spices", "other"];
const labels: Record<string, string> = { produce: "Produce", protein: "Protein", dairy: "Dairy", grains: "Grains", pantry: "Pantry", spices: "Spices", other: "Other" };
function monday() { const d = new Date(); const day = d.getDay(); d.setDate(d.getDate() - (day === 0 ? 6 : day - 1)); return d.toISOString().slice(0, 10); }

export default function GroceryPage() {
  const weekStart = monday(); const [items, setItems] = useState<GroceryListItem[]>([]); const [custom, setCustom] = useState(""); const [category, setCategory] = useState("pantry"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch(`/api/grocery?weekStart=${weekStart}`); const data = await r.json() as { items?: GroceryListItem[]; message?: string }; if (!r.ok) throw new Error(data.message ?? "Unable to load grocery list."); setItems(data.items ?? []); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to load grocery list."); } finally { setLoading(false); } }, [weekStart]);
  useEffect(() => { void load(); }, [load]);
  async function save(next: GroceryListItem[]) { setSaving(true); setError(""); try { const r = await fetch("/api/grocery", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ weekStart, items: next }) }); const data = await r.json() as { items?: GroceryListItem[]; message?: string }; if (!r.ok) throw new Error(data.message ?? "Unable to save grocery list."); setItems(data.items ?? next); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to save grocery list."); } finally { setSaving(false); } }
  function add() { if (!custom.trim()) return; void save([...items, { id: `custom-${Date.now()}`, name: custom.trim(), category, quantity: "1", checked: false }]); setCustom(""); }
  async function generate() { setSaving(true); setError(""); setMessage(""); try { const r = await fetch("/api/grocery", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ weekStart }) }); const data = await r.json() as { items?: GroceryListItem[]; message?: string }; if (!r.ok) throw new Error(data.message ?? "Unable to generate list."); setItems(data.items ?? []); setMessage("Grocery list generated from your meal plan!"); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to generate list."); } finally { setSaving(false); } }
  async function update(item: GroceryListItem, patch: Partial<GroceryListItem>) { setSaving(true); try { const r = await fetch("/api/grocery", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ weekStart, id: item.id, ...patch }) }); const data = await r.json() as { items?: GroceryListItem[]; message?: string }; if (!r.ok) throw new Error(data.message ?? "Unable to update item."); setItems(data.items ?? items); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Unable to update item."); } finally { setSaving(false); } }
  async function remove(id: string) { const r = await fetch(`/api/grocery?weekStart=${weekStart}&id=${encodeURIComponent(id)}`, { method: "DELETE" }); if (r.ok) setItems((await r.json()).items ?? items); else setError((await r.json()).message ?? "Unable to remove item."); }
  async function clearCompleted() { const r = await fetch(`/api/grocery?weekStart=${weekStart}&clearCompleted=true`, { method: "DELETE" }); if (r.ok) setItems((await r.json()).items ?? []); else setError((await r.json()).message ?? "Unable to clear items."); }
  const groups = useMemo(() => categories.map((value) => ({ value, items: items.filter((item) => item.category === value) })).filter((group) => group.items.length), [items]);
  const completed = items.filter((item) => item.checked).length;
  return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Take it to the store</div><h1>Your grocery list.</h1><p>Generate ingredients from your plan, then add anything else you want to bring home.</p></div><span className="pill">{items.length - completed} left · {completed} completed</span></div>{message && <div className="toast" role="status">{message}</div>}{error && <div className="error-box" role="alert">{error}</div>}<div className="app-card"><div className="toolbar"><input className="input search-input" value={custom} onChange={(e) => setCustom(e.target.value)} onKeyDown={(e) => e.key === "Enter" && add()} placeholder="Add an item…" /><select className="select" value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select><button className="button button-ghost" onClick={add} disabled={saving}>Add item</button><button className="button button-primary" onClick={() => void generate()} disabled={saving}>Generate from meal plan</button>{completed > 0 && <button className="button button-ghost" onClick={() => void clearCompleted()} disabled={saving}>Clear completed</button>}</div>{loading ? <div className="loading-state">Loading your grocery list…</div> : items.length === 0 ? <div className="empty-state"><strong>Your list is empty</strong><span>Generate it from this week&apos;s plan or add your own item.</span></div> : <div className="grocery-groups">{groups.map((group) => <section key={group.value}><h2 className="section-title">{labels[group.value]}</h2>{group.items.map((item) => <div className="grocery-item" key={item.id}><input type="checkbox" checked={item.checked} onChange={() => void update(item, { checked: !item.checked })} aria-label={`Mark ${item.name} complete`} /><input className={`input grocery-name ${item.checked ? "grocery-done" : ""}`} value={item.name} onChange={(e) => setItems((current) => current.map((x) => x.id === item.id ? { ...x, name: e.target.value } : x))} onBlur={(e) => void update(item, { name: e.target.value })} /><input className="input grocery-quantity" value={item.quantity} onChange={(e) => setItems((current) => current.map((x) => x.id === item.id ? { ...x, quantity: e.target.value } : x))} onBlur={(e) => void update(item, { quantity: e.target.value })} aria-label={`Quantity for ${item.name}`} /><select className="select grocery-category" value={item.category} onChange={(e) => void update(item, { category: e.target.value })} aria-label={`Category for ${item.name}`}>{categories.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select><button className="delete-button" type="button" onClick={() => void remove(item.id)}>Remove</button></div>)}</section>)}</div>}</div></div>;
}
